/**
 * Study plan utilities: detect concept keywords in plan text and match to resource links.
 * Keyword matching is case-insensitive. No links are generated by AI; only conceptResources used.
 */

import { conceptResources } from "../data/conceptResources";

/**
 * Find all concept keywords that appear in text (case-insensitive).
 * Returns unique matches in order of first appearance in text.
 * Longer concept names are preferred when one is a substring of another
 * (e.g. "Dynamic Programming" over "Programming").
 *
 * @param {string} text - Study plan segment (e.g. day1, day2, day3)
 * @param {Record<string, string>} [resources] - Concept -> URL map (default: conceptResources)
 * @returns {{ concept: string, url: string }[]}
 */
export function getConceptLinksForText(text, resources = conceptResources) {
  if (!text || typeof text !== "string") return [];

  const lower = text.toLowerCase();
  const concepts = Object.keys(resources);

  // Sort by length descending so "Dynamic Programming" is checked before "Programming"
  const sortedConcepts = [...concepts].sort((a, b) => b.length - a.length);

  const seen = new Set();
  const result = [];

  for (const concept of sortedConcepts) {
    if (seen.has(concept)) continue;
    if (!concept || !resources[concept]) continue;

    if (lower.includes(concept.toLowerCase())) {
      seen.add(concept);
      result.push({ concept, url: resources[concept] });
    }
  }

  return result;
}

/**
 * Given one day's study plan text, return the same text plus a list of resource links
 * for any detected concepts. Used to render the plan and inject links below it.
 *
 * @param {string} dayText - Raw study plan string for one day
 * @param {Record<string, string>} [resources] - Concept -> URL map
 * @returns {{ text: string, links: { concept: string, url: string }[] }}
 */
export function getStudyPlanDayWithLinks(dayText, resources = conceptResources) {
  const text = dayText != null ? String(dayText) : "";
  const links = getConceptLinksForText(text, resources);
  return { text, links };
}
